source "https://rubygems.org"

gem "fastlane", "~> 2.220"

# Fastlane plugins
gem "fastlane-plugin-flutter_version", "~> 1.1"

# Additional gems for better performance and compatibility
gem "cocoapods", "~> 1.15" if RUBY_PLATFORM.include?("darwin")
gem "rexml", "~> 3.2"
